### ISSUE TITLE
Dupe When KeepInventoty is Active

### ISSUE THREAD

**Issue by xpd207** [mk7a/ItemSoulBind#17]
I have tested the last version of this plugin and i cold see an issue, my players reported-me item dupe, becouse the keepinventory is activated.

**Comment by mk7a** [comment]
This is not helpful, fill out the bug report template with instructions on how to reproduce the bug so that I can investigate.

**Comment by mk7a** [comment]
**Plugin version**
Get plugin version with /ver ItemSoulBind
**Spigot Version**
Get spigot version with /ver

**Plugin Configuration**
<details>
  <summary>File</summary>
   paste your plugin config here
</details>

**Plugins List**
If you are running other plugins, please provide a list.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem e.g. console error stacktrace

**Additional context**
Add any other context about the problem here.
