### ISSUE TITLE
Bug with elytra

### ISSUE THREAD

**Issue by msmanui** [mk7a/ItemSoulBind#18]
Im using the lastest version (1.1.1) with paper 1.16.4. 

If u put an elytra into an chest and then someone else comes and do "F+CLICK" it will add to the inventory (visually) but he would be able to fly.

**Comment by mk7a** [comment]
I have tried to reproduce this, it is a client side effect only, the person does not actually have the elytra in their in hand. 
If this is different from what you are experiencing, please properly provide the necessary bug report details

<details>
  <summary>Bug report</summary>

**Plugin version**
Get plugin version with /ver ItemSoulBind
**Spigot Version**
Get spigot version with /ver

**Plugin Configuration**
<details>
  <summary>File</summary>
   paste your plugin config here
</details>

**Plugins List**
If you are running other plugins, please provide a list.

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem e.g. console error stacktrace

**Additional context**
Add any other context about the problem here.
</details>
